name: MCDiscordBot
version: 1.0
author: SEPT_Mg
main: site.septmg.mcDiscordBot.Main
commands:

  discord:
    description: send discord message
    aliases: ds

  discordReload:
    description: reload the config.yml
    aliases: [dsrl,discordrl,dsreload]